### ISSUE TITLE
Saving/restoring machine state between runs

### ISSUE THREAD

**Issue by xtovski** [StoneCypher/jssm#513] opened 2022-07-08 17:09 UTC
Is there any better clear strategy of saving and restoring machine state between instances than saving `state()` and restoring with `force_transition()`?

I am currently using mentioned above methods, but the only drawback I see if that I do not save/restore any data besides states, and also `force_transition()` is causing entry hooks to fire up, which doesn't make any sense as they have already been fired up in previous run.

**Comment by StoneCypher** [comment] 2022-07-08 19:17
No.  This had never occurred to me.  I'll make one promptly, which also preserves data state and history, so that there's a clear expected behavior as other unrelated things like tape come online.

Besides not retriggering hooks, are there any other considerations you want me to bear in mind during?

I track stuff in the FSL issue tracker, so I'm going to open an issue there.  Commentary is requested there: https://github.com/StoneCypher/fsl/issues/999

Closing this issue in favor of the new issue in the other repo.

**Closed** 2022-07-08 19:17 UTC

**Comment by StoneCypher** [comment] 2022-07-08 19:19
This is a good idea and a fairly important thing.  I'm glad it's not going to be omitted much longer

**Comment by StoneCypher** [comment] 2022-07-09 23:25
@xtovski - draft implementation available, please update.  API should be stable.

```javascript

const machine_string = 'a 'next' <-> 'next' b;';

const foo = jssm.from(machine_string, { history: 5, data: 2 });

foo.do('next'); 
foo.do('next'); 
foo.do('next'); 

const ser = foo.serialize();

const bar = jssm.deserialize(machine_string, ser);
```

**Comment by xtovski** [comment] 2022-07-11 17:22
Thank you for your response. Yes, proposed API looks exactly like something I was thinking about.

**Comment by StoneCypher** [comment] 2022-07-11 17:33
Great.  There's some other stuff going in later, like version locking, and support for some features that aren't actually in the machine (eg tape) yet

But I guess I think this is sufficiently tested, and usable

One minor caveat: because serialization needs to be usable between two unrelated javascript contexts, there's no practical way to re-bind the functions.  You will need to set the hooks again, after deserializing.  So far, I don't see any way around that.

**Comment by StoneCypher** [comment] 2022-07-11 17:41
or, actually, can you generate once with the newer api that has the extra parameter, then manually edit the .d.ts and mark that parameter optional, maybe?

**Comment by xtovski** [comment] 2022-07-11 18:46
Yes, you are correct. I am re-binding all hooks in a state machine factory I made to do all serialization/de-serialization tasks.

**Comment by StoneCypher** [comment] 2022-07-11 18:53
Cool.

I really appreciate your help, letting me know things my machine is missing.  Please let me know what else needs to be here.
